admin:
   email: sunblack1978@gmail.com
   secret_google: secrets.json
   gdrive_dir: Magento-Backup
   log: logs/backupMagento.log
mysql:
   host: localhost
   user: root
   passwd: '@medparc123'
   database: magento
   port: 3306
magento:
   ssh_host: localhost 
   ssh_user:
   ssh_pass:
   ssh_port:
   path: /var/www/html/zapGroup/
backup:
   mysql_rotation: 10 
   magento_rotation: 10
   storage_local: False
   storage: storage/
